(** Translations between groupoid-valued face presentations and
    pseudofunctors into [HGpd2Cat]. The exchange paths determine the word
    compositor, and the face hexagon supplies its associativity. *)

Set Warnings "-notation-overridden".
From Bonak.Lib Require Import RewLemmas.
From Bonak Require Import HSet Notation LeSProp Funext.
From Bonak Require Import νGpd.HGpd.
From Bonak.Presheaf.Gpd Require Export Presentation.

From Bonak.Category Require Import Category.
From Bonak.Category.Bicategory Require Import Bicategory.
From Bonak.Presheaf Require Import νSemiShape WordAction WordCoherence.
From Stdlib Require Import Logic.FunctionalExtensionality.

From Bonak.Category.Bicategory Require Import LocallyDiscrete Pseudofunctor
  LocallyDiscretePseudofunctor.

From Bonak.Category.Bicategory Require Import PathDiagramLemmas.

From Bonak.Category.Bicategory Require Import HGpd2Cat.

Set Primitive Projections.
Set Printing Projections.

Definition gpdStr {A: HSet} (P: νGpdPresentation A): FaceStr A := {|
  S0 n := P.(G0) n;
  SFace := P.(GFace);
|}.

(** The face hexagon supplies associativity of the word compositor. *)

Section PshGpdCoherence.
Context {A: HSet} (P: νGpdPresentation A).

Definition gpdCoh: CohOf (gpdStr P) := P.(GFaceCoh).

Definition gpdCoh2: Coh2Of gpdCoh := P.(GFaceCoh2).

Definition pshGpdComp {p m n} (g: Word A m p) (f: Word A n m)
  (x: (gpdStr P).(S0) p):
  applyW m f (gpdStr P) (applyW p g (gpdStr P) x)
  = applyW p (wcomp g f) (gpdStr P) x :=
  applyWComp p m n g f (gpdStr P) gpdCoh x.

Definition pshGpdAssoc {r p m n} (h: Word A p r) (g: Word A m p)
  (f: Word A n m) (x: (gpdStr P).(S0) r):
  f_equal (applyW m f (gpdStr P)) (pshGpdComp h g x)
  • pshGpdComp (wcomp h g) f x
  = pshGpdComp g f (applyW r h (gpdStr P) x)
    • (pshGpdComp h (wcomp g f) x
       • f_equal (fun w => applyW r w (gpdStr P) x) (wcompAssoc h g f)) :=
  applyWAssoc r p m n h g f (gpdStr P) gpdCoh gpdCoh2 x.

End PshGpdCoherence.

Section PresheafGpdPseudofunctor.
Context (A: HSet).

(** The arrow action, identity equality and compositor generated by a face
    structure with an exchange law. Their construction does not require
    the hexagon; associativity is established separately.

    The canonical identity witness uses the computational form of functional
    extensionality, so evaluation recovers [applyW_id]. *)

Definition toPsfStrWithUnit {ob: nat -> HGpd}
  (SF: GFaceType A ob) (HQ: CohOf (Build_FaceStr A ob SF))
  (unit: forall n, applyW n (wid n) (Build_FaceStr A ob SF) = (fun x: ob n => x)):
  PathDiagramData (Op (νSemiShape A)) ob :=
  Build_PathDiagramData (Op (νSemiShape A)) ob
    (fun a b w => applyW a w (Build_FaceStr A ob SF)) unit
    (fun a b c f g x => applyWComp a b c f g (Build_FaceStr A ob SF) HQ x).

Definition toPsfStr {ob: nat -> HGpd}
  (SF: GFaceType A ob) (HQ: CohOf (Build_FaceStr A ob SF)):
  PathDiagramData (Op (νSemiShape A)) ob :=
  toPsfStrWithUnit SF HQ (fun n => functional_extensionality_dep_good _ _
    (fun x => applyW_id (Build_FaceStr A ob SF) x)).

(** The pseudofunctor structure of a groupoid-valued presheaf. *)

Definition toPsfOn (P: νGpdPresentation A):
  PathDiagramData (Op (νSemiShape A)) P.(G0) :=
  toPsfStr P.(GFace) P.(GFaceCoh).

(** From a pseudofunctor to a record: restrict to the generating cofaces. The
    exchange law is the compositor at the two-letter words, read across the
    defining relation of the ν-semi-shape category. *)

Section OfPsf.
Context (ob: nat -> HGpd) (F: PathDiagramData (Op (νSemiShape A)) ob).

Definition ofPsfFace n q (Hq: q <= n) (ε: A): ob (S n) -> ob n :=
  F.(phom) (a := S n) (b := n) (wgen n q ε).

Lemma ofPsfCoh n q (Hq: q <= n) r (Hr: r <= q) (ε ω: A) (X: ob (S (S n))):
  ofPsfFace n q Hq ε (ofPsfFace (S n) r (Hr ↕ (↑ Hq)) ω X)
  = ofPsfFace n r (Hr ↕ Hq) ω (ofPsfFace (S n) (S q) (⇑ Hq) ε X).
Proof.
  refine (F.(pcomp) (a := S (S n)) (b := S n) (c := n)
            (wgen (S n) r ω) (wgen n q ε) X • _).
  refine (f_equal (fun w => F.(phom) (a := S (S n)) (b := n) w X)
            (wgenExchange n q Hq r Hr ε ω) • _).
  now exact (eq_sym (F.(pcomp) (a := S (S n)) (b := S n) (c := n)
                       (wgen (S n) (S q) ε) (wgen n r ω) X)).
Defined.

(** The two whiskerings of an exchange cell, in the shape the hexagon uses. *)

Lemma ofPsfCohWhiskerL n p (Hp: p <= n) q (Hq: q <= S n) r (Hr: r <= q)
  (η ε ω: A) (X: ob (S (S (S n)))):
  f_equal (ofPsfFace n p Hp η) (ofPsfCoh (S n) q Hq r Hr ε ω X)
  = psfComp3 F (wgen (S (S n)) r ω) (wgen (S n) q ε) (wgen n p η) X
    • (f_equal (fun z => F.(phom) z X)
        (f_equal (fun z: (Op (νSemiShape A)).(CHom) (S (S (S n))) (S n) =>
                    z ⨟ wgen n p η)
           (wgenExchange (S n) q Hq r Hr ε ω))
       • eq_sym (psfComp3 F (wgen (S (S n)) (S q) ε) (wgen (S n) r ω)
                   (wgen n p η) X)).
Proof.
  now exact (pcompWhiskerL F (wgenExchange (S n) q Hq r Hr ε ω) (wgen n p η) X
    (F.(pcomp) (wgen (S (S n)) r ω) (wgen (S n) q ε) X)
    (F.(pcomp) (wgen (S (S n)) (S q) ε) (wgen (S n) r ω) X)).
Defined.

Lemma ofPsfCohWhiskerR (FA: PathDiagramAssoc (Op (νSemiShape A)) ob F)
  n q (Hq: q <= n) r (Hr: r <= q) p (Hp: p <= S (S n)) (ε ω η: A)
  (X: ob (S (S (S n)))):
  ofPsfCoh n q Hq r Hr ε ω (ofPsfFace (S (S n)) p Hp η X)
  = psfComp3 F (wgen (S (S n)) p η) (wgen (S n) r ω) (wgen n q ε) X
    • (f_equal (fun z => F.(phom) z X)
        ((Op (νSemiShape A)).(cassoc) (wgen (S (S n)) p η) (wgen (S n) r ω)
           (wgen n q ε)
         • (f_equal (fun z: (Op (νSemiShape A)).(CHom) (S (S n)) n =>
                       @ccomp (Op (νSemiShape A)) (S (S (S n))) (S (S n)) n
                         (wgen (S (S n)) p η) z)
              (wgenExchange n q Hq r Hr ε ω)
            • eq_sym ((Op (νSemiShape A)).(cassoc) (wgen (S (S n)) p η)
                        (wgen (S n) (S q) ε) (wgen n r ω))))
       • eq_sym (psfComp3 F (wgen (S (S n)) p η) (wgen (S n) (S q) ε)
                   (wgen n r ω) X)).
Proof.
  now exact (pcompWhiskerR F FA (wgen (S (S n)) p η)
    (wgenExchange n q Hq r Hr ε ω) X).
Defined.

(** The hexagon. Each of its six sides conjugates an equality of words by the
    three-fold compositors at its endpoints, so both routes are the conjugation
    of a composite equality between the same two words; the hom-types of the
    ν-semi-shape category are h-sets, so those two equalities agree. *)

Lemma ofPsfCoh2 (FA: PathDiagramAssoc (Op (νSemiShape A)) ob F)
  n q (Hq: q <= n) r (Hr: r <= q) s (Hs: s <= r) (ε ω θ: A)
  (X: ob (S (S (S n)))):
  f_equal (ofPsfFace n q Hq ε) (ofPsfCoh (S n) r (Hr ↕ (↑ Hq)) s Hs ω θ X)
  • (ofPsfCoh n q Hq s (Hs ↕ Hr) ε θ
      (ofPsfFace (S (S n)) (S r) (⇑ (Hr ↕ (↑ Hq))) ω X)
  • f_equal (ofPsfFace n s (Hs ↕ (Hr ↕ Hq)) θ)
      (ofPsfCoh (S n) (S q) (⇑ Hq) (S r) (⇑ Hr) ε ω X)) =
  ofPsfCoh n q Hq r Hr ε ω (ofPsfFace (S (S n)) s (↑ (↑ (Hs ↕ (Hr ↕ Hq)))) θ X)
  • (f_equal (ofPsfFace n r (Hr ↕ Hq) ω)
      (ofPsfCoh (S n) (S q) (⇑ Hq) s (↑ (Hs ↕ Hr)) ε θ X)
  • ofPsfCoh n r (Hr ↕ Hq) s Hs ω θ
      (ofPsfFace (S (S n)) (S (S q)) (⇑ (⇑ Hq)) ε X)).
Proof.
  rewrite (ofPsfCohWhiskerL n q Hq r (Hr ↕ (↑ Hq)) s Hs ε ω θ X).
  rewrite (ofPsfCohWhiskerR FA n q Hq s (Hs ↕ Hr) (S r)
             (⇑ (Hr ↕ (↑ Hq))) ε θ ω X).
  rewrite (ofPsfCohWhiskerL n s (Hs ↕ (Hr ↕ Hq)) (S q) (⇑ Hq) (S r) (⇑ Hr)
             θ ε ω X).
  rewrite (ofPsfCohWhiskerR FA n q Hq r Hr s (↑ (↑ (Hs ↕ (Hr ↕ Hq))))
             ε ω θ X).
  rewrite (ofPsfCohWhiskerL n r (Hr ↕ Hq) (S q) (⇑ Hq) s (↑ (Hs ↕ Hr))
             ω ε θ X).
  rewrite (ofPsfCohWhiskerR FA n r (Hr ↕ Hq) s Hs (S (S q)) (⇑ (⇑ Hq))
             ω θ ε X).
  rewrite !conjTrans3.
  apply conjCancel.
  now apply (fEqualUIP
    (fun x y h g => ((Op (νSemiShape A)).(CHom) (S (S (S n))) n).(UIP))
    (fun z: (Op (νSemiShape A)).(CHom) (S (S (S n))) n => F.(phom) z X)).
Qed.

End OfPsf.

(** The record read off a path diagram. *)

Definition ofPsf (ob: nat -> HGpd) (F: PathDiagram (Op (νSemiShape A)) ob):
  νGpdPresentation A :=
  let S := pathData (Op (νSemiShape A)) ob F in
  Build_νGpdPresentation A ob (ofPsfFace ob S) (ofPsfCoh ob S)
    (ofPsfCoh2 ob S (pathAssoc (Op (νSemiShape A)) ob F)).

End PresheafGpdPseudofunctor.

Section PseudofunctorLaws.
Context (A: HSet).

(** The source associativity path agrees with [wcompAssoc] by hom-set
    UIP, so the pointwise law follows from associativity of the word action. *)

Lemma toPsfAssoc (P: νGpdPresentation A):
  PathDiagramAssoc (Op (νSemiShape A)) P.(G0) (toPsfOn A P).
Proof.
  apply pathDiagramAssocOfPt. intros a b c d f g h E x.
  rewrite (((Op (νSemiShape A)).(CHom) a d).(UIP)
    (h := E) (g := eq_sym (wcompAssoc f g h))).
  unfold phomEq.
  change (f_equal (applyW c h (gpdStr P)) (pshGpdComp P f g x)
    • (pshGpdComp P (wcomp f g) h x
       • f_equal (fun w => applyW a w (gpdStr P) x) (eq_sym (wcompAssoc f g h)))
    = pshGpdComp P g h (applyW a f (gpdStr P) x)
       • pshGpdComp P f (wcomp g h) x).
  rewrite <- eqTransAssoc, (pshGpdAssoc P f g h x), eq_trans_assoc, fEqualSym.
  apply transSymCancelR.
Qed.

(** The unit axioms

    The compositor of the generated pseudofunctor at an identity word is the
    unit law of the action, so the two unit axioms hold as soon as the
    unit witness [pid] can be evaluated at a point. That witness is
    functional extensionality applied to the identity homotopy of the action
    of the identity word, and what the axioms consume is exactly its
    computation rule; it is therefore taken here as a parameter, together with
    the rule. *)

Definition toPsfOnW (P: νGpdPresentation A)
  (pidW: forall a, applyW a (wid a) (gpdStr P) = (fun x: P.(G0) a => x)):
  PathDiagramData (Op (νSemiShape A)) P.(G0) :=
  toPsfStrWithUnit A P.(GFace) P.(GFaceCoh) pidW.

Lemma toPsfUnitLW (P: νGpdPresentation A) pidW
  (HpidW: forall a x, happly (pidW a) x = applyW_id (gpdStr P) x):
  PathDiagramUnitL (Op (νSemiShape A)) P.(G0) (toPsfOnW P pidW).
Proof.
  apply pathDiagramUnitLOfPt. intros a b f E x.
  apply (transCancelR _ _ (phomEq (toPsfOnW P pidW) E x)).
  rewrite transSymCancelR2.
  unfold pidPt, phomEq.
  change (applyWComp a a b (wid a) f (gpdStr P) P.(GFaceCoh) x
    • f_equal (fun w => applyW a w (gpdStr P) x) E = f_equal (applyW a f (gpdStr P)) (happly (pidW a) x)).
  rewrite HpidW.
  rewrite (((Op (νSemiShape A)).(CHom) a b).(UIP)
    (h := E) (g := wcompIdl f)).
  exact (applyWCompIdL A a b f (gpdStr P) P.(GFaceCoh) x).
Qed.

Lemma toPsfUnitRW (P: νGpdPresentation A) pidW
  (HpidW: forall a x, happly (pidW a) x = applyW_id (gpdStr P) x):
  PathDiagramUnitR (Op (νSemiShape A)) P.(G0) (toPsfOnW P pidW).
Proof.
  apply pathDiagramUnitROfPt. intros a b f E x.
  apply (transCancelR _ _ (phomEq (toPsfOnW P pidW) E x)).
  rewrite transSymCancelR2.
  unfold pidPt, phomEq.
  change (applyWComp a b b f (wid b) (gpdStr P) P.(GFaceCoh) x
    • f_equal (fun w => applyW a w (gpdStr P) x) E = happly (pidW b) (applyW a f (gpdStr P) x)).
  rewrite HpidW.
  rewrite (((Op (νSemiShape A)).(CHom) a b).(UIP)
    (h := E) (g := wcompIdr f)).
  exact (applyWCompIdR A a b f (gpdStr P) P.(GFaceCoh) x).
Qed.

(** The unit path of [toPsfOn] and its computation rule. *)

Definition toPsfPid (P: νGpdPresentation A) (a: nat):
  applyW a (wid a) (gpdStr P) = (fun x: P.(G0) a => x) :=
  functional_extensionality_dep_good _ _ (fun x => applyW_id (gpdStr P) x).

Lemma toPsfPidComp (P: νGpdPresentation A) (a: nat) (x: P.(G0) a):
  happly (toPsfPid P a) x = applyW_id (gpdStr P) x.
Proof.
  now exact (f_equal__functional_extensionality_dep_good
    (fun y => applyW_id (gpdStr P) y) x).
Qed.

Lemma toPsfUnitL (P: νGpdPresentation A):
  PathDiagramUnitL (Op (νSemiShape A)) P.(G0) (toPsfOn A P).
Proof. now exact (toPsfUnitLW P (toPsfPid P) (toPsfPidComp P)). Qed.

Lemma toPsfUnitR (P: νGpdPresentation A):
  PathDiagramUnitR (Op (νSemiShape A)) P.(G0) (toPsfOn A P).
Proof. now exact (toPsfUnitRW P (toPsfPid P) (toPsfPidComp P)). Qed.

Definition toPsf (P: νGpdPresentation A): PathDiagram (Op (νSemiShape A)) P.(G0) :=
  Build_PathDiagram (Op (νSemiShape A)) P.(G0) (toPsfOn A P) (toPsfUnitL P)
    (toPsfUnitR P) (toPsfAssoc P).

End PseudofunctorLaws.

Section PackagedTranslations.
Context (A: HSet).

Definition toPsfTot (P: νGpdPresentation A): PathDiagramFamily (Op (νSemiShape A)) :=
  Build_PathDiagramFamily (Op (νSemiShape A)) P.(G0) (toPsf A P).

Definition ofPsfTot (X: PathDiagramFamily (Op (νSemiShape A))): νGpdPresentation A :=
  ofPsf A X.(pfObj) X.(pfStr).

End PackagedTranslations.

(** The translations with their full 2-cell action and unit comparisons. *)

Definition toPseudofunctor (A: HSet) (P: νGpdPresentation A):
  Pseudofunctor (locallyDiscrete (Op (νSemiShape A))) HGpd2Cat :=
  expandPseudofunctor (toPsfTot A P).

Definition ofPseudofunctor (A: HSet)
  (F: Pseudofunctor (locallyDiscrete (Op (νSemiShape A))) HGpd2Cat): νGpdPresentation A :=
  ofPsfTot A (contractPseudofunctor F).
