(** Both round trips between face presentations and pseudofunctors. *)

Set Warnings "-notation-overridden".
From Bonak.Lib Require Import HSet Notation LeSProp Equiv.
From Bonak.νGpd Require Import HGpd.

From Bonak.Category Require Import Category.
From Bonak.Category.Bicategory Require Import Bicategory IconPath LocallyDiscrete Pseudofunctor
  LocallyDiscretePseudofunctor.
From Bonak.Presheaf Require Import νSemiShape WordAction GeneratorCoherence.
From Bonak.Presheaf.Gpd Require Import Icon.
From Bonak.Presheaf.Gpd Require Export Pseudofunctor.

From Bonak.Category.Bicategory Require Import PathDiagram.

From Bonak.Category.Bicategory Require Import HGpd2Cat.

Set Primitive Projections.
Set Printing Projections.

Section GpdRoundtrip.
Context (A: HSet).

(** The round trip on records *)

Lemma toPsfCohEq (P: PresheafGpd A) (n q: nat) (Hq: q <= n) (r: nat) (Hr: r <= q)
  (ε ω: A) (X: P.(G0) (S (S n))):
  ofPsfCoh A P.(G0) (toPsfOn A P) n q Hq r Hr ε ω X
  • (applyWgen A (gpdStr P) n r (Hr ↕ Hq) ω
       (ofPsfFace A P.(G0) (toPsfOn A P) (S n) (S q) (⇑ Hq) ε X)
     • f_equal (P.(GFace) n r (Hr ↕ Hq) ω)
         (applyWgen A (gpdStr P) (S n) (S q) (⇑ Hq) ε X))
  = (applyWgen A (gpdStr P) n q Hq ε
       (ofPsfFace A P.(G0) (toPsfOn A P) (S n) r (Hr ↕ (↑ Hq)) ω X)
     • f_equal (P.(GFace) n q Hq ε)
         (applyWgen A (gpdStr P) (S n) r (Hr ↕ (↑ Hq)) ω X))
    • P.(GFaceCoh) n q Hq r Hr ε ω X.
Proof.
  now exact (applyWgenCoh A n (gpdStr P) P.(GFaceCoh) q Hq r Hr ε ω X).
Qed.

Lemma ofToPsfOn (P: PresheafGpd A)
  (D: GCoh2Type A (ofPsfCoh A P.(G0) (toPsfOn A P))):
  Build_PresheafGpd A P.(G0) (ofPsfFace A P.(G0) (toPsfOn A P))
    (ofPsfCoh A P.(G0) (toPsfOn A P)) D = P.
Proof.
  now exact (gpdEqHom A (ofPsfFace A P.(G0) (toPsfOn A P)) P.(GFace)
    (ofPsfCoh A P.(G0) (toPsfOn A P)) P.(GFaceCoh) D P.(GFaceCoh2)
    (fun n q Hq ε x => applyWgen A (gpdStr P) n q Hq ε x)
    (toPsfCohEq P)).
Qed.

Lemma ofToPsf (P: PresheafGpd A): ofPsf A P.(G0) (toPsf A P) = P.
Proof. now exact (ofToPsfOn P _). Qed.

(** The pseudofunctor generated by the faces of [F] is [F] itself. The icon
    between them has the identity object part, so the object parts agree
    without transport. *)

Lemma toOfPsf (X: PathDiagramFamily (Op (νSemiShape A))):
  toPsfTot A (ofPsfTot A X) = X.
Proof.
  destruct X as [ob F].
  now exact (f_equal (Build_PathDiagramFamily (Op (νSemiShape A)) ob)
    (iconPath (toPsf A (ofPsf A ob F)) F (psfIcon A F))).
Defined.

End GpdRoundtrip.

(** The inverse laws for unrestricted pseudofunctors. *)

Definition ofToPseudofunctor (A: HSet) (P: PresheafGpd A):
  ofPseudofunctor A (toPseudofunctor A P) = P :=
  f_equal (ofPsfTot A)
    (retEq (locallyDiscretePseudofunctorEquiv (Op (νSemiShape A))) (toPsfTot A P))
  • ofToPsf A P.

Definition toOfPseudofunctor (A: HSet)
  (F: Pseudofunctor (locallyDiscrete (Op (νSemiShape A))) HGpd2Cat):
  toPseudofunctor A (ofPseudofunctor A F) = F :=
  f_equal (@expandPseudofunctor (Op (νSemiShape A)))
    (toOfPsf A (contractPseudofunctor F))
  • secEq (locallyDiscretePseudofunctorEquiv (Op (νSemiShape A))) F.
