name: rocq-action

on:
  push:
    paths:
      - "**.v"
      - "bonak.opam"
      - "dune-project"
      - "**/dune"
      - ".github/workflows/coq-action.yml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "**.v"
      - "bonak.opam"
      - "dune-project"
      - "**/dune"
      - ".github/workflows/coq-action.yml"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "true"
      - name: "Docker Rocq action"
        uses: "coq-community/docker-coq-action@v1"
        with:
          opam_file: "bonak.opam"
          coq_version: "9.2"
          before_install: |
            startGroup "Configure opam"
              if opam pin list --short | grep -qx dune; then
                opam unpin -y dune
              fi
              opam config list
              opam repo list
              opam list
            endGroup
          install: |
            startGroup "Install dependencies"
              sudo apt-get update -y -q
              opam pin add -n -y -k path $PACKAGE $WORKDIR
              opam update -y default
              opam install --confirm-level=unsafe-yes -j 2 $PACKAGE --deps-only
            endGroup
